// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuMFV-02gYB2aZCPF7ubVl83j2_Bk72_I',
    appId: '1:544452989761:web:f99042b3c5f8effcd687c0',
    messagingSenderId: '544452989761',
    projectId: 'academyplatform-12c05',
    authDomain: 'academyplatform-12c05.firebaseapp.com',
    storageBucket: 'academyplatform-12c05.firebasestorage.app',
    measurementId: 'G-K3V8EJ403Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBujGidZkxPYcEW0chrOVUGDIVbMVoudT4',
    appId: '1:544452989761:android:28670bfb98154771d687c0',
    messagingSenderId: '544452989761',
    projectId: 'academyplatform-12c05',
    storageBucket: 'academyplatform-12c05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaV5OaQMQtFgKCccS_pzdYVIg6VqRsm4s',
    appId: '1:544452989761:ios:8e5807241ac342d0d687c0',
    messagingSenderId: '544452989761',
    projectId: 'academyplatform-12c05',
    storageBucket: 'academyplatform-12c05.firebasestorage.app',
    iosBundleId: 'com.example.academyPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaV5OaQMQtFgKCccS_pzdYVIg6VqRsm4s',
    appId: '1:544452989761:ios:8e5807241ac342d0d687c0',
    messagingSenderId: '544452989761',
    projectId: 'academyplatform-12c05',
    storageBucket: 'academyplatform-12c05.firebasestorage.app',
    iosBundleId: 'com.example.academyPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuMFV-02gYB2aZCPF7ubVl83j2_Bk72_I',
    appId: '1:544452989761:web:b7c2523d9c5fc174d687c0',
    messagingSenderId: '544452989761',
    projectId: 'academyplatform-12c05',
    authDomain: 'academyplatform-12c05.firebaseapp.com',
    storageBucket: 'academyplatform-12c05.firebasestorage.app',
    measurementId: 'G-Z66YLT1Z2P',
  );
}
